version: "3.9"
services:
  hub-validator-1:
    container_name: hub-validator-1
    image: dymensionxyz/dymension
    ports:
      - "26657:26657"
      - "1317:1317"
      - "9090:9090"
    environment:
      - MONIKER_NAME=hub-validator-1
      - IS_GENESIS_VALIDATOR=true # only set this to true for one validator which is in charge of creating the genesis file
      - VALIDATOR_COUNT=2
    volumes:
      - hub:/home/shared
      - ./hub-entrypoint.sh:/hub-entrypoint.sh
      - ./sequencer-hub.pk:/sequencer-hub.pk
    entrypoint: sh -c /hub-entrypoint.sh
  hub-validator-2:
    container_name: hub-validator-2
    image: dymensionxyz/dymension
    ports:
      - "26658:26657"
      - "1318:1317"
      - "9091:9090"
    environment:
      - MONIKER_NAME=hub-validator-2
      - VALIDATOR_COUNT=2
    volumes:
      - hub:/home/shared
      - ./hub-entrypoint.sh:/hub-entrypoint.sh
    entrypoint: sh -c /hub-entrypoint.sh

  rollapp-a-sequencer:
    container_name: rollapp-a-sequencer
    image: dymensionxyz/rollapp
    ports:
      - "26659:26657"
      - "1319:1317"
      - "9092:9090"
    environment:
      - MONIKER_NAME=rollapp-a-sequencer
      - IS_GENESIS_SEQUENCER=true # only set this to true for one validator which is in charge of creating the genesis file
      - NODE_COUNT=1
      - AGGREGATOR=true
      - DA_LAYER=mock
      - DA_LAYER_CONFIG=30000ms
      - SETTLEMENT_LAYER=mock
    volumes:
      - rollapp-a:/home/shared
      - ./rollapp-entrypoint.sh:/rollapp-entrypoint.sh
      - ./sequencer-hub.pk:/sequencer-hub.pk
    entrypoint: bash -c /rollapp-entrypoint.sh

volumes:
  hub:
  rollapp-a: